version: '3.8'

services:
  # Infrastructure Services
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: globaltaxcalc
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - globaltaxcalc-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - globaltaxcalc-network

  mongodb:
    image: mongo:7
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - globaltaxcalc-network

  # API Gateway
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    networks:
      - globaltaxcalc-network
    volumes:
      - ./api-gateway:/app
      - /app/node_modules

  # Authentication Service
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/globaltaxcalc
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your-jwt-secret-key
    depends_on:
      - postgres
      - redis
    networks:
      - globaltaxcalc-network
    volumes:
      - ./auth-service:/app
      - /app/node_modules

  # Tax Engine Service (Python)
  tax-engine:
    build:
      context: ./tax-engine
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHON_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/globaltaxcalc
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    networks:
      - globaltaxcalc-network
    volumes:
      - ./tax-engine:/app

  # Geolocation Service
  geolocation-service:
    build:
      context: ./geolocation-service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - PORT=3002
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/globaltaxcalc
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    networks:
      - globaltaxcalc-network
    volumes:
      - ./geolocation-service:/app
      - /app/node_modules

  # AI Service (Python)
  ai-service:
    build:
      context: ./ai-service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - PYTHON_ENV=development
      - MONGODB_URL=mongodb://mongo:mongo@mongodb:27017/globaltaxcalc
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongodb
      - redis
    networks:
      - globaltaxcalc-network
    volumes:
      - ./ai-service:/app

  # Content Service
  content-service:
    build:
      context: ./content-service
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - PORT=3003
      - MONGODB_URL=mongodb://mongo:mongo@mongodb:27017/globaltaxcalc
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongodb
      - redis
    networks:
      - globaltaxcalc-network
    volumes:
      - ./content-service:/app
      - /app/node_modules

  # Analytics Service
  analytics-service:
    build:
      context: ./analytics-service
      dockerfile: Dockerfile
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=development
      - PORT=3004
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/globaltaxcalc
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    networks:
      - globaltaxcalc-network
    volumes:
      - ./analytics-service:/app
      - /app/node_modules

  # Notification Service
  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=development
      - PORT=3005
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/globaltaxcalc
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    networks:
      - globaltaxcalc-network
    volumes:
      - ./notification-service:/app
      - /app/node_modules

  # Ad Service
  ad-service:
    build:
      context: ./ad-service
      dockerfile: Dockerfile
    ports:
      - "3006:3006"
    environment:
      - NODE_ENV=development
      - PORT=3006
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/globaltaxcalc
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    networks:
      - globaltaxcalc-network
    volumes:
      - ./ad-service:/app
      - /app/node_modules

  # File Service
  file-service:
    build:
      context: ./file-service
      dockerfile: Dockerfile
    ports:
      - "3007:3007"
    environment:
      - NODE_ENV=development
      - PORT=3007
      - MONGODB_URL=mongodb://mongo:mongo@mongodb:27017/globaltaxcalc
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongodb
      - redis
    networks:
      - globaltaxcalc-network
    volumes:
      - ./file-service:/app
      - /app/node_modules

  # Report Service (Python)
  report-service:
    build:
      context: ./report-service
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    environment:
      - PYTHON_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/globaltaxcalc
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    networks:
      - globaltaxcalc-network
    volumes:
      - ./report-service:/app

  # Monitoring Service
  monitoring-service:
    build:
      context: ./monitoring-service
      dockerfile: Dockerfile
    ports:
      - "3008:3008"
    environment:
      - NODE_ENV=development
      - PORT=3008
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/globaltaxcalc
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    networks:
      - globaltaxcalc-network
    volumes:
      - ./monitoring-service:/app
      - /app/node_modules

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3009:3009"
    environment:
      - NODE_ENV=development
      - PORT=3009
      - NEXT_PUBLIC_API_URL=http://localhost:3000
    depends_on:
      - api-gateway
    networks:
      - globaltaxcalc-network
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next

volumes:
  postgres_data:
  redis_data:
  mongodb_data:

networks:
  globaltaxcalc-network:
    driver: bridge