# Elasticsearch Configuration for GlobalTaxCalc Search

# Cluster Configuration
cluster.name: globaltaxcalc-cluster
node.name: es-node-1
node.roles: [master, data, ingest, ml]

# Network Configuration
network.host: 0.0.0.0
http.port: 9200
transport.port: 9300

# Discovery Configuration
discovery.type: single-node
cluster.initial_master_nodes: ["es-node-1"]

# Memory Configuration
bootstrap.memory_lock: true
indices.memory.index_buffer_size: 20%
indices.memory.min_index_buffer_size: 96mb

# Performance Settings
thread_pool.search.size: 8
thread_pool.search.queue_size: 1000
thread_pool.write.size: 4
thread_pool.write.queue_size: 200

# Index Settings
indices.queries.cache.size: 15%
indices.fielddata.cache.size: 25%
indices.requests.cache.size: 5%

# Circuit Breaker Settings
indices.breaker.total.limit: 85%
indices.breaker.fielddata.limit: 40%
indices.breaker.request.limit: 40%

# Query Settings
search.max_buckets: 65536
search.default_search_timeout: 5s
search.max_open_scroll_context: 500

# Indexing Settings
index.refresh_interval: 1s
index.number_of_shards: 2
index.number_of_replicas: 1
index.max_result_window: 50000

# Logging Configuration
logger.level: INFO
logger.org.elasticsearch.discovery: DEBUG

# Security Configuration (disabled for development)
xpack.security.enabled: false
xpack.security.enrollment.enabled: false
xpack.security.http.ssl.enabled: false
xpack.security.transport.ssl.enabled: false

# Machine Learning Configuration
xpack.ml.enabled: true
xpack.ml.node_concurrent_job_allocations: 1

# Monitoring Configuration
xpack.monitoring.enabled: true
xpack.monitoring.collection.enabled: true

# Watcher Configuration (for alerts)
xpack.watcher.enabled: true

# License Configuration
xpack.license.self_generated.type: basic

# Cross-Cluster Replication
xpack.ccr.enabled: false

# Snapshot and Restore
path.repo: ["/usr/share/elasticsearch/backups"]

# Index Lifecycle Management
xpack.ilm.enabled: true

# Rollup Configuration
xpack.rollup.enabled: true

# SQL Configuration
xpack.sql.enabled: true

# Graph Configuration
xpack.graph.enabled: true

# Custom Settings for Tax Search
# Synonym files location
path.conf: /usr/share/elasticsearch/config

# Custom analyzers and filters configuration
index.analysis.analyzer.default.type: standard
index.analysis.analyzer.default.stopwords: _english_

# Allocation awareness
cluster.routing.allocation.awareness.attributes: zone
cluster.routing.allocation.awareness.force.zone.values: zone1,zone2

# Slow log configuration
index.search.slowlog.threshold.query.warn: 2s
index.search.slowlog.threshold.query.info: 1s
index.search.slowlog.threshold.fetch.warn: 1s
index.search.slowlog.threshold.fetch.info: 500ms
index.indexing.slowlog.threshold.index.warn: 2s
index.indexing.slowlog.threshold.index.info: 1s

# Recovery settings
indices.recovery.max_bytes_per_sec: 100mb
cluster.routing.allocation.node_concurrent_recoveries: 2

# Cache settings
indices.queries.cache.count: 10000
indices.fielddata.cache.expire: 1h

# Merge settings
index.merge.policy.max_merged_segment: 2gb
index.merge.policy.segments_per_tier: 8